FULL_DATASET_PATH = "dataset/full"
SAMPLE_DATASET_PATH = "dataset/sample"
MODELS_DIR = "./saved_models/"
RESIZE_WIDTH = 32
RESIZE_HEIGHT = 32
TESTING_SET_SIZE_FACTOR = 0.25
TRAINING_SET_SIZE_FACTOR = 1 - TESTING_SET_SIZE_FACTOR
